-- NEED initial schema draft for MySQL 8.
-- This migration is a planning artifact only in round 7.
-- Do not execute until a real migration tool and database connection are introduced.

CREATE TABLE admin_users (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(80) NOT NULL,
  display_name VARCHAR(120) NOT NULL,
  email VARCHAR(180) NULL,
  password_hash VARCHAR(255) NOT NULL,
  role VARCHAR(40) NOT NULL DEFAULT 'editor',
  status VARCHAR(30) NOT NULL DEFAULT 'active',
  last_login_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at DATETIME NULL,
  UNIQUE KEY uk_admin_users_username (username),
  UNIQUE KEY uk_admin_users_email (email),
  KEY idx_admin_users_status (status),
  KEY idx_admin_users_deleted_at (deleted_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE media_files (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  file_name VARCHAR(255) NOT NULL,
  original_name VARCHAR(255) NOT NULL,
  file_path VARCHAR(600) NOT NULL,
  public_url VARCHAR(800) NULL,
  mime_type VARCHAR(120) NOT NULL,
  file_ext VARCHAR(30) NULL,
  file_size BIGINT UNSIGNED NOT NULL DEFAULT 0,
  width INT UNSIGNED NULL,
  height INT UNSIGNED NULL,
  duration_seconds DECIMAL(10,2) NULL,
  category VARCHAR(60) NOT NULL DEFAULT 'general',
  alt_text VARCHAR(255) NULL,
  description TEXT NULL,
  source VARCHAR(120) NULL,
  storage_provider VARCHAR(30) NOT NULL DEFAULT 'local',
  usage_count INT UNSIGNED NOT NULL DEFAULT 0,
  status VARCHAR(30) NOT NULL DEFAULT 'active',
  uploaded_by BIGINT UNSIGNED NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at DATETIME NULL,
  KEY idx_media_files_category (category),
  KEY idx_media_files_status (status),
  KEY idx_media_files_uploaded_by (uploaded_by),
  KEY idx_media_files_deleted_at (deleted_at),
  CONSTRAINT fk_media_files_uploaded_by FOREIGN KEY (uploaded_by) REFERENCES admin_users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE home_interactive_images (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  slot_number TINYINT UNSIGNED NOT NULL,
  media_id BIGINT UNSIGNED NULL,
  image_url VARCHAR(800) NULL,
  alt_text VARCHAR(255) NULL,
  sort_order INT NOT NULL DEFAULT 0,
  is_enabled TINYINT(1) NOT NULL DEFAULT 1,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at DATETIME NULL,
  UNIQUE KEY uk_home_interactive_images_slot (slot_number),
  KEY idx_home_interactive_images_media_id (media_id),
  KEY idx_home_interactive_images_sort_order (sort_order),
  KEY idx_home_interactive_images_enabled (is_enabled),
  KEY idx_home_interactive_images_deleted_at (deleted_at),
  CONSTRAINT chk_home_interactive_images_slot CHECK (slot_number BETWEEN 1 AND 12),
  CONSTRAINT fk_home_interactive_images_media FOREIGN KEY (media_id) REFERENCES media_files(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE home_video (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  video_media_id BIGINT UNSIGNED NULL,
  poster_media_id BIGINT UNSIGNED NULL,
  video_url VARCHAR(800) NULL,
  poster_url VARCHAR(800) NULL,
  title VARCHAR(180) NULL,
  description TEXT NULL,
  is_enabled TINYINT(1) NOT NULL DEFAULT 1,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at DATETIME NULL,
  KEY idx_home_video_enabled (is_enabled),
  KEY idx_home_video_deleted_at (deleted_at),
  CONSTRAINT fk_home_video_video_media FOREIGN KEY (video_media_id) REFERENCES media_files(id),
  CONSTRAINT fk_home_video_poster_media FOREIGN KEY (poster_media_id) REFERENCES media_files(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE pages (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(180) NOT NULL,
  slug VARCHAR(180) NOT NULL,
  summary TEXT NULL,
  status VARCHAR(30) NOT NULL DEFAULT 'draft',
  sort_order INT NOT NULL DEFAULT 0,
  is_system_page TINYINT(1) NOT NULL DEFAULT 0,
  published_at DATETIME NULL,
  created_by BIGINT UNSIGNED NULL,
  updated_by BIGINT UNSIGNED NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at DATETIME NULL,
  UNIQUE KEY uk_pages_slug (slug),
  KEY idx_pages_status (status),
  KEY idx_pages_sort_order (sort_order),
  KEY idx_pages_deleted_at (deleted_at),
  CONSTRAINT fk_pages_created_by FOREIGN KEY (created_by) REFERENCES admin_users(id),
  CONSTRAINT fk_pages_updated_by FOREIGN KEY (updated_by) REFERENCES admin_users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE page_blocks (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  page_id BIGINT UNSIGNED NOT NULL,
  block_type VARCHAR(80) NOT NULL,
  block_data_json JSON NOT NULL,
  sort_order INT NOT NULL DEFAULT 0,
  is_enabled TINYINT(1) NOT NULL DEFAULT 1,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at DATETIME NULL,
  KEY idx_page_blocks_page_id (page_id),
  KEY idx_page_blocks_type (block_type),
  KEY idx_page_blocks_sort_order (sort_order),
  KEY idx_page_blocks_deleted_at (deleted_at),
  CONSTRAINT fk_page_blocks_page FOREIGN KEY (page_id) REFERENCES pages(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE cases (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(220) NOT NULL,
  slug VARCHAR(180) NOT NULL,
  summary TEXT NULL,
  client_type VARCHAR(120) NULL,
  event_type VARCHAR(120) NULL,
  event_time VARCHAR(120) NULL,
  event_location VARCHAR(180) NULL,
  cover_media_id BIGINT UNSIGNED NULL,
  cover_url VARCHAR(800) NULL,
  project_goal TEXT NULL,
  client_need TEXT NULL,
  our_scope TEXT NULL,
  execution_challenge TEXT NULL,
  solution_summary TEXT NULL,
  live_highlight TEXT NULL,
  final_result TEXT NULL,
  status VARCHAR(30) NOT NULL DEFAULT 'draft',
  sort_order INT NOT NULL DEFAULT 0,
  is_home_featured TINYINT(1) NOT NULL DEFAULT 0,
  published_at DATETIME NULL,
  created_by BIGINT UNSIGNED NULL,
  updated_by BIGINT UNSIGNED NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at DATETIME NULL,
  UNIQUE KEY uk_cases_slug (slug),
  KEY idx_cases_status (status),
  KEY idx_cases_sort_order (sort_order),
  KEY idx_cases_home_featured (is_home_featured),
  KEY idx_cases_deleted_at (deleted_at),
  CONSTRAINT fk_cases_cover_media FOREIGN KEY (cover_media_id) REFERENCES media_files(id),
  CONSTRAINT fk_cases_created_by FOREIGN KEY (created_by) REFERENCES admin_users(id),
  CONSTRAINT fk_cases_updated_by FOREIGN KEY (updated_by) REFERENCES admin_users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE case_blocks (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  case_id BIGINT UNSIGNED NOT NULL,
  block_type VARCHAR(80) NOT NULL,
  block_data_json JSON NOT NULL,
  sort_order INT NOT NULL DEFAULT 0,
  is_enabled TINYINT(1) NOT NULL DEFAULT 1,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at DATETIME NULL,
  KEY idx_case_blocks_case_id (case_id),
  KEY idx_case_blocks_type (block_type),
  KEY idx_case_blocks_sort_order (sort_order),
  KEY idx_case_blocks_deleted_at (deleted_at),
  CONSTRAINT fk_case_blocks_case FOREIGN KEY (case_id) REFERENCES cases(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE case_images (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  case_id BIGINT UNSIGNED NOT NULL,
  media_id BIGINT UNSIGNED NULL,
  image_url VARCHAR(800) NULL,
  alt_text VARCHAR(255) NULL,
  caption VARCHAR(255) NULL,
  sort_order INT NOT NULL DEFAULT 0,
  is_enabled TINYINT(1) NOT NULL DEFAULT 1,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at DATETIME NULL,
  KEY idx_case_images_case_id (case_id),
  KEY idx_case_images_media_id (media_id),
  KEY idx_case_images_sort_order (sort_order),
  KEY idx_case_images_deleted_at (deleted_at),
  CONSTRAINT fk_case_images_case FOREIGN KEY (case_id) REFERENCES cases(id),
  CONSTRAINT fk_case_images_media FOREIGN KEY (media_id) REFERENCES media_files(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE article_categories (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(120) NOT NULL,
  slug VARCHAR(180) NOT NULL,
  description TEXT NULL,
  sort_order INT NOT NULL DEFAULT 0,
  status VARCHAR(30) NOT NULL DEFAULT 'active',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at DATETIME NULL,
  UNIQUE KEY uk_article_categories_slug (slug),
  KEY idx_article_categories_status (status),
  KEY idx_article_categories_sort_order (sort_order),
  KEY idx_article_categories_deleted_at (deleted_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE articles (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  category_id BIGINT UNSIGNED NULL,
  title VARCHAR(220) NOT NULL,
  slug VARCHAR(180) NOT NULL,
  summary TEXT NULL,
  cover_media_id BIGINT UNSIGNED NULL,
  cover_url VARCHAR(800) NULL,
  tags_json JSON NULL,
  status VARCHAR(30) NOT NULL DEFAULT 'draft',
  sort_order INT NOT NULL DEFAULT 0,
  is_home_featured TINYINT(1) NOT NULL DEFAULT 0,
  published_at DATETIME NULL,
  created_by BIGINT UNSIGNED NULL,
  updated_by BIGINT UNSIGNED NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at DATETIME NULL,
  UNIQUE KEY uk_articles_slug (slug),
  KEY idx_articles_category_id (category_id),
  KEY idx_articles_status (status),
  KEY idx_articles_sort_order (sort_order),
  KEY idx_articles_home_featured (is_home_featured),
  KEY idx_articles_deleted_at (deleted_at),
  CONSTRAINT fk_articles_category FOREIGN KEY (category_id) REFERENCES article_categories(id),
  CONSTRAINT fk_articles_cover_media FOREIGN KEY (cover_media_id) REFERENCES media_files(id),
  CONSTRAINT fk_articles_created_by FOREIGN KEY (created_by) REFERENCES admin_users(id),
  CONSTRAINT fk_articles_updated_by FOREIGN KEY (updated_by) REFERENCES admin_users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE article_blocks (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  article_id BIGINT UNSIGNED NOT NULL,
  block_type VARCHAR(80) NOT NULL,
  block_data_json JSON NOT NULL,
  sort_order INT NOT NULL DEFAULT 0,
  is_enabled TINYINT(1) NOT NULL DEFAULT 1,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at DATETIME NULL,
  KEY idx_article_blocks_article_id (article_id),
  KEY idx_article_blocks_type (block_type),
  KEY idx_article_blocks_sort_order (sort_order),
  KEY idx_article_blocks_deleted_at (deleted_at),
  CONSTRAINT fk_article_blocks_article FOREIGN KEY (article_id) REFERENCES articles(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE solutions (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(180) NOT NULL,
  slug VARCHAR(180) NOT NULL,
  summary TEXT NULL,
  cover_media_id BIGINT UNSIGNED NULL,
  cover_url VARCHAR(800) NULL,
  status VARCHAR(30) NOT NULL DEFAULT 'draft',
  sort_order INT NOT NULL DEFAULT 0,
  published_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at DATETIME NULL,
  UNIQUE KEY uk_solutions_slug (slug),
  KEY idx_solutions_status (status),
  KEY idx_solutions_sort_order (sort_order),
  KEY idx_solutions_deleted_at (deleted_at),
  CONSTRAINT fk_solutions_cover_media FOREIGN KEY (cover_media_id) REFERENCES media_files(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE solution_pages (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  solution_id BIGINT UNSIGNED NOT NULL,
  title VARCHAR(220) NOT NULL,
  slug VARCHAR(180) NOT NULL,
  summary TEXT NULL,
  cover_media_id BIGINT UNSIGNED NULL,
  cover_url VARCHAR(800) NULL,
  status VARCHAR(30) NOT NULL DEFAULT 'draft',
  sort_order INT NOT NULL DEFAULT 0,
  published_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at DATETIME NULL,
  UNIQUE KEY uk_solution_pages_solution_slug (solution_id, slug),
  KEY idx_solution_pages_solution_id (solution_id),
  KEY idx_solution_pages_status (status),
  KEY idx_solution_pages_sort_order (sort_order),
  KEY idx_solution_pages_deleted_at (deleted_at),
  CONSTRAINT fk_solution_pages_solution FOREIGN KEY (solution_id) REFERENCES solutions(id),
  CONSTRAINT fk_solution_pages_cover_media FOREIGN KEY (cover_media_id) REFERENCES media_files(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE solution_page_blocks (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  solution_page_id BIGINT UNSIGNED NOT NULL,
  block_type VARCHAR(80) NOT NULL,
  block_data_json JSON NOT NULL,
  sort_order INT NOT NULL DEFAULT 0,
  is_enabled TINYINT(1) NOT NULL DEFAULT 1,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at DATETIME NULL,
  KEY idx_solution_page_blocks_page_id (solution_page_id),
  KEY idx_solution_page_blocks_type (block_type),
  KEY idx_solution_page_blocks_sort_order (sort_order),
  KEY idx_solution_page_blocks_deleted_at (deleted_at),
  CONSTRAINT fk_solution_page_blocks_page FOREIGN KEY (solution_page_id) REFERENCES solution_pages(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE faq_items (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  owner_type VARCHAR(60) NOT NULL,
  owner_id BIGINT UNSIGNED NOT NULL,
  question VARCHAR(300) NOT NULL,
  answer TEXT NOT NULL,
  sort_order INT NOT NULL DEFAULT 0,
  status VARCHAR(30) NOT NULL DEFAULT 'active',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at DATETIME NULL,
  KEY idx_faq_items_owner (owner_type, owner_id),
  KEY idx_faq_items_status (status),
  KEY idx_faq_items_sort_order (sort_order),
  KEY idx_faq_items_deleted_at (deleted_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE seo_settings (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  owner_type VARCHAR(60) NOT NULL,
  owner_id BIGINT UNSIGNED NOT NULL,
  title VARCHAR(255) NULL,
  description TEXT NULL,
  keywords TEXT NULL,
  canonical VARCHAR(800) NULL,
  robots VARCHAR(120) NOT NULL DEFAULT 'index,follow',
  structured_data_type VARCHAR(80) NULL,
  structured_data_json JSON NULL,
  sitemap_priority DECIMAL(2,1) NOT NULL DEFAULT 0.5,
  sitemap_changefreq VARCHAR(30) NOT NULL DEFAULT 'monthly',
  og_title VARCHAR(255) NULL,
  og_description TEXT NULL,
  og_image_media_id BIGINT UNSIGNED NULL,
  og_image_url VARCHAR(800) NULL,
  published_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at DATETIME NULL,
  UNIQUE KEY uk_seo_settings_owner (owner_type, owner_id),
  KEY idx_seo_settings_owner (owner_type, owner_id),
  KEY idx_seo_settings_deleted_at (deleted_at),
  CONSTRAINT fk_seo_settings_og_image FOREIGN KEY (og_image_media_id) REFERENCES media_files(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE publish_logs (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  publish_version VARCHAR(80) NOT NULL,
  publish_type VARCHAR(40) NOT NULL DEFAULT 'full',
  target_type VARCHAR(60) NULL,
  target_id BIGINT UNSIGNED NULL,
  status VARCHAR(30) NOT NULL DEFAULT 'pending',
  release_dir VARCHAR(500) NULL,
  previous_version VARCHAR(80) NULL,
  rollback_to_version VARCHAR(80) NULL,
  summary TEXT NULL,
  error_message TEXT NULL,
  started_at DATETIME NULL,
  finished_at DATETIME NULL,
  created_by BIGINT UNSIGNED NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at DATETIME NULL,
  UNIQUE KEY uk_publish_logs_version (publish_version),
  KEY idx_publish_logs_status (status),
  KEY idx_publish_logs_target (target_type, target_id),
  KEY idx_publish_logs_created_by (created_by),
  KEY idx_publish_logs_deleted_at (deleted_at),
  CONSTRAINT fk_publish_logs_created_by FOREIGN KEY (created_by) REFERENCES admin_users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE site_settings (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  setting_key VARCHAR(120) NOT NULL,
  setting_value_json JSON NOT NULL,
  group_name VARCHAR(80) NOT NULL DEFAULT 'general',
  description VARCHAR(255) NULL,
  is_public TINYINT(1) NOT NULL DEFAULT 1,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at DATETIME NULL,
  UNIQUE KEY uk_site_settings_key (setting_key),
  KEY idx_site_settings_group (group_name),
  KEY idx_site_settings_deleted_at (deleted_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE redirects (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  from_path VARCHAR(500) NOT NULL,
  to_path VARCHAR(500) NOT NULL,
  status_code SMALLINT UNSIGNED NOT NULL DEFAULT 301,
  reason VARCHAR(255) NULL,
  is_enabled TINYINT(1) NOT NULL DEFAULT 1,
  created_by BIGINT UNSIGNED NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at DATETIME NULL,
  UNIQUE KEY uk_redirects_from_path (from_path),
  KEY idx_redirects_enabled (is_enabled),
  KEY idx_redirects_deleted_at (deleted_at),
  CONSTRAINT fk_redirects_created_by FOREIGN KEY (created_by) REFERENCES admin_users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE audit_logs (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  admin_user_id BIGINT UNSIGNED NULL,
  action VARCHAR(120) NOT NULL,
  target_type VARCHAR(60) NULL,
  target_id BIGINT UNSIGNED NULL,
  request_method VARCHAR(20) NULL,
  request_path VARCHAR(500) NULL,
  ip_address VARCHAR(80) NULL,
  user_agent VARCHAR(500) NULL,
  before_json JSON NULL,
  after_json JSON NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at DATETIME NULL,
  KEY idx_audit_logs_admin_user_id (admin_user_id),
  KEY idx_audit_logs_action (action),
  KEY idx_audit_logs_target (target_type, target_id),
  KEY idx_audit_logs_created_at (created_at),
  KEY idx_audit_logs_deleted_at (deleted_at),
  CONSTRAINT fk_audit_logs_admin_user FOREIGN KEY (admin_user_id) REFERENCES admin_users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
